### ISSUE TITLE
The container image referenced in this example is not available

### ISSUE THREAD

**Issue by shivkumarr** [mptaws/secret-ecs-cdk-example#2]
The container image referenced in this example is not available anymore

https://github.com/mptaws/secret-ecs-cdk-example/blob/b17f42dbf37639d7ef1ac57bdc5805be8074a09b/cdk.json#L15 

    "containerImage": "public.ecr.aws/o0u3i9v5/secret-ecs-repo"

**Comment by mptaws** [comment]
Isengard images are no longer public - switched to docker hub.   Please try again.
